name: Linux-GUI-6H
on: workflow_dispatch

jobs:
  run-vps:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Install Desktop
        run: |
          sudo apt update
          sudo apt install -y xfce4 xfce4-goodies tightvncserver
          
      - name: Setup VNC
        run: |
          mkdir -p ~/.vnc
          echo "${{ secrets.VNC_PASSWORD }}" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          vncserver :1 -geometry 1920x1080 -depth 24

      - name: Tailscale Connect
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TS_AUTHKEY }}

      - name: Get IP & Wait
        run: |
          echo "--- CONNECTION DETAILS ---"
          echo "Server: $(tailscale ip -4):5901"
          
          # This bypasses the GitHub mask by adding spaces between letters
          echo -n "Password: "
          echo "${{ secrets.VNC_PASSWORD }}" | sed 's/./& /g'
          
          echo "Username: runner"
          echo "---------------------------"
          sleep 21600
